name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    # - name: Build project
    #   run: |
    #     npm run build
    #     cp package.json dist/
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: dist

    - name: Deploy to GCP
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_FUNCTION_NAME: ${{ secrets.GCP_FUNCTION_NAME }}
        GCP_REGION: ${{ secrets.GCP_REGION }}
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo $HOME
        echo $GCP_CREDENTIALS > ${HOME}/gcloud.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
        gcloud config set project $GCP_PROJECT
        gcloud functions deploy $GCP_FUNCTION_NAME --runtime nodejs14 --trigger-http --allow-unauthenticated --region $GCP_REGION --source /home/runner/work/practice/practice
