name: Build

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      ARTIFACT_NAME: ${{ steps.set-output.outputs.ARTIFACT_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Build project
      run: |
        npm run build
      
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: build-artifacts
    #     path: dist

    # - name: Download build artifacts
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: build-artifacts
    #     path: dist
    - name: Generate unique artifact name
      id: set-output
      run: echo "ARTIFACT_NAME=build-artifact-${{ github.run_number }}.zip" >> $GITHUB_OUTPUT
      
    - name: Zip project
      run: zip -r ${{ steps.set-output.outputs.ARTIFACT_NAME }} .

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ${{ steps.set-output.outputs.ARTIFACT_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
       name: build-artifacts
       path: ./
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Artifact upload to Google storage bucket
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: ${{ needs.build.outputs.ARTIFACT_NAME }}
        destination: 'node-artifact'

    - name: Deploy to GCP
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_FUNCTION_NAME: ${{ secrets.GCP_FUNCTION_NAME }}
        GCP_REGION: ${{ secrets.GCP_REGION }}
      run: |
        echo $HOME
        pwd
        gcloud config set project $GCP_PROJECT
        gcloud functions add-iam-policy-binding $GCP_FUNCTION_NAME \
        --region $GCP_REGION \
        --member="allUsers" \
        --role="roles/cloudfunctions.invoker"
        gcloud functions deploy $GCP_FUNCTION_NAME --runtime nodejs16 --trigger-http --allow-unauthenticated --region $GCP_REGION --source gs://node-artifact/${{ needs.build.outputs.ARTIFACT_NAME }}
