name: Deploy to GCP Cloud Functions

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: dist

    - name: Deploy to GCP
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_FUNCTION_NAME: ${{ secrets.GCP_FUNCTION_NAME }}
        GCP_REGION: ${{ secrets.GCP_REGION }}
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo $GCP_CREDENTIALS > ${HOME}/gcloud.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
        gcloud config set project $GCP_PROJECT
        gcloud functions deploy $GCP_FUNCTION_NAME --runtime nodejs14 --trigger-http --allow-unauthenticated --region $GCP_REGION --source dist
